### GET (Basic)
http://localhost:5000

### Get Users
http://localhost:5000/api/users

### GET Users (Protected Route)
GET http://localhost:5000/api/users HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdyZWciLCJkZXBhcnRtZW50IjoiTXVzaWMiLCJpYXQiOjE1NjA0MzkxOTUsImV4cCI6MTU2MDQ0NjM5NSwic3ViIjoiNiJ9.ntV4CwnaDMSJcfa5EFw8FT7v0QrSLkNvhs7WH6S7sTw

### GET Users (by ID)
http://localhost:5000/api/users/1

### (Register) POST 
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
  "username": "Greg",
  "password": "pass123",
  "department": "Music"
}

### (Login) POST 
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "Mike",
  "password": "pass"
}

### (Logout) GET 
http://localhost:5000/api/auth/logout

### (User Update) PUT 
PUT http://localhost:5000/api/users/6 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdyZWciLCJkZXBhcnRtZW50IjoiTXVzaWMiLCJpYXQiOjE1NjA0MzkxOTUsImV4cCI6MTU2MDQ0NjM5NSwic3ViIjoiNiJ9.ntV4CwnaDMSJcfa5EFw8FT7v0QrSLkNvhs7WH6S7sTw
content-type: application/json

{
  "username": "Greg",
  "department": "Music"
}

### DELETE (Users)
DELETE http://localhost:5000/api/users/600
